[default]

# DEFININDO A LINGUAGEM UTILIZADA NO MODELO SPACY
LANGUAGE = "portuguese"

# DEFININDO AS BASES A SEREM UTILIZADAS
PATH_DATA_TRAIN = "BASES/BASE_TREINAMENTO.txt"
PATH_DATA_TEST = "BASES/BASE_TESTE.txt"

# NOME DAS COLUNAS DO DATAFRAME
NAME_COLUMN_TEXT = 'texto'
NAME_COLUMN_EMOTION = 'emocao'

# NOME DAS COLUNAS QUE RECEBERÁO OS RESULTADOS DE PRÉ PROCESSAMENTO
VARIABLES = "texto_formatado"
TARGET = "emocao_formatado"

# DEFININDO A QUANTIDADE DE EPOCHS E BATCHS
EPOCHS = 1000
BATCH_SIZE = 30

# DEFININDO OS LABELS DO MODELO
TEXT_CAT = "textcat"
MODEL_LABEL = ["ALEGRIA", "MEDO"]

# DEFININDO O LOCAL DE SAVE DO MODELO
DIR_SAVE = "RESULTADOS/MODEL"

# DEFININDO O NOME DO RESULTADO DE SAVE NOS TESTES
TEST_RESULT_DEFAULT = {ALEGRIA = '', MEDO = ''}


[development]
