[default]

# DEFININDO A LINGUAGEM UTILIZADA NO MODELO SPACY
LANGUAGE = "portuguese"

# DEFININDO AS bases A SEREM UTILIZADAS
PATH_DATA_TRAIN = "BASES/BASE_TREINAMENTO.txt"
PATH_DATA_TEST = "BASES/BASE_TESTE.txt"

[development]
